[build-system]
requires = ["setuptools >= 64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name="ionmaidentools"
version="0.0.1"
description="Necroflow pipeline definitions and CLI wrapper tools for the ionmaiden project."
readme="README.md"
authors=[
    {name="MatteoLacki",email="matteo.lacki@gmail.com"},
]
requires-python = ">=3.11"
dependencies = [
    "tomlkit",
]

[project.optional-dependencies]
dev = [
    "pytest",
]


[project.scripts]
necromerge2-stage-dir = "ionmaidentools.cli.necromerge2_stage_dir:main"
necromerge2-run-mkpmsms = "ionmaidentools.cli.necromerge2_run_mkpmsms:main"
necromerge2-stage-sage-input = "ionmaidentools.cli.necromerge2_stage_sage_input:main"
necromerge2-run-sage = "ionmaidentools.cli.necromerge2_run_sage:main"
necromerge2-extract-config = "ionmaidentools.cli.necromerge2_extract_config:main"

[project.urls]
homepage="https://github.com/MatteoLacki/ionmaidentools.git"
repository="https://github.com/MatteoLacki/ionmaidentools.git"

[tool.uv]
reinstall-package = ["ionmaidentools"]

# [tool.pytest.ini_options]
# testpaths = ["tests"]


[tool.setuptools.packages.find]
where = ["src"]

# [tool.setuptools]
# include-package-data = true

# [tool.setuptools.package-data]
# ionmaidentools = ["data/*.csv"]
